export declare const ErrorCodes: {
    readonly UNIT_OCCUPIED: "UNIT_OCCUPIED";
    readonly UNIT_NOT_AVAILABLE: "UNIT_NOT_AVAILABLE";
    readonly UNIT_CODE_DUPLICATE: "UNIT_CODE_DUPLICATE";
    readonly RESERVATION_EXPIRED: "RESERVATION_EXPIRED";
    readonly RESERVATION_HOLD_CONFLICT: "RESERVATION_HOLD_CONFLICT";
    readonly AGREEMENT_PREREQUISITE_MISSING: "AGREEMENT_PREREQUISITE_MISSING";
    readonly AGREEMENT_NOT_ACTIVE: "AGREEMENT_NOT_ACTIVE";
    readonly MANDATE_INCOMPLETE: "MANDATE_INCOMPLETE";
    readonly INVOICE_DUPLICATE_PERIOD: "INVOICE_DUPLICATE_PERIOD";
    readonly INVOICE_ALREADY_SETTLED: "INVOICE_ALREADY_SETTLED";
    readonly CREDIT_NOTE_EXCEEDS_BALANCE: "CREDIT_NOTE_EXCEEDS_BALANCE";
    readonly PERMISSION_DENIED: "PERMISSION_DENIED";
    readonly SITE_SCOPE_VIOLATION: "SITE_SCOPE_VIOLATION";
    readonly RATE_RULE_OVERLAP: "RATE_RULE_OVERLAP";
    readonly TRANSFER_TARGET_UNAVAILABLE: "TRANSFER_TARGET_UNAVAILABLE";
    readonly INSPECTION_REQUIRED: "INSPECTION_REQUIRED";
    readonly LEGAL_HOLD_ACTIVE: "LEGAL_HOLD_ACTIVE";
};
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
//# sourceMappingURL=error-codes.d.ts.map