export const ErrorCodes = {
  UNIT_OCCUPIED: 'UNIT_OCCUPIED',
  UNIT_NOT_AVAILABLE: 'UNIT_NOT_AVAILABLE',
  UNIT_CODE_DUPLICATE: 'UNIT_CODE_DUPLICATE',
  RESERVATION_EXPIRED: 'RESERVATION_EXPIRED',
  RESERVATION_HOLD_CONFLICT: 'RESERVATION_HOLD_CONFLICT',
  AGREEMENT_PREREQUISITE_MISSING: 'AGREEMENT_PREREQUISITE_MISSING',
  AGREEMENT_NOT_ACTIVE: 'AGREEMENT_NOT_ACTIVE',
  MANDATE_INCOMPLETE: 'MANDATE_INCOMPLETE',
  INVOICE_DUPLICATE_PERIOD: 'INVOICE_DUPLICATE_PERIOD',
  INVOICE_ALREADY_SETTLED: 'INVOICE_ALREADY_SETTLED',
  CREDIT_NOTE_EXCEEDS_BALANCE: 'CREDIT_NOTE_EXCEEDS_BALANCE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SITE_SCOPE_VIOLATION: 'SITE_SCOPE_VIOLATION',
  RATE_RULE_OVERLAP: 'RATE_RULE_OVERLAP',
  TRANSFER_TARGET_UNAVAILABLE: 'TRANSFER_TARGET_UNAVAILABLE',
  INSPECTION_REQUIRED: 'INSPECTION_REQUIRED',
  LEGAL_HOLD_ACTIVE: 'LEGAL_HOLD_ACTIVE',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
