import Link from 'next/link';
import { BrandLogo } from '@/components/brand-logo';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-100 py-4 px-6">
        <div className="max-w-3xl mx-auto flex justify-between items-center">
          <BrandLogo href="/" compact markClassName="h-7 w-7" />
          <Link href="/legal/terms" className="text-sm text-slate-500 hover:text-slate-700">Terms of Service</Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-slate-400 mb-8">Last updated: May 2026</p>
        <div className="prose prose-slate max-w-none text-slate-600 space-y-6">
          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-2">1. Who we are</h2>
            <p>SiteLager is a SaaS platform and marketplace for storage operators and tenants, operated from the European Union. This privacy policy explains how we collect, use, and protect your personal data in accordance with the GDPR.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-2">2. Data we collect</h2>
            <p>We collect data you provide directly (name, email, address, payment details), data generated by your use of our service (activity logs, invoices, access events), and technical data (IP address, browser type, session data).</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-2">3. Legal basis for processing</h2>
            <p>We process your data on the basis of contract performance, legitimate interests, and — where required — explicit consent. You may withdraw consent at any time.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-2">4. Your rights</h2>
            <p>Under GDPR you have the right to access, rectify, erase, restrict, and port your data. Contact us at privacy@sitelager.com to exercise your rights.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-2">5. Retention</h2>
            <p>We retain personal data for as long as necessary to fulfil the purposes for which it was collected, or as required by law (e.g. invoice data for 10 years under German tax law).</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-2">6. Contact</h2>
            <p>For privacy enquiries contact: <a href="mailto:privacy@sitelager.com" className="text-blue-600 hover:underline">privacy@sitelager.com</a></p>
          </section>
        </div>
      </main>
    </div>
  );
}
