export const CHECKLISTS: Record<string, { code: string; i18nKey: string }[]> = {
  move_in: [
    { code: 'PHOTOS',    i18nKey: 'PHOTOS_UPLOADED' },
    { code: 'CLEAN',     i18nKey: 'UNIT_CLEAN' },
    { code: 'DOOR',      i18nKey: 'DOOR_WORKING' },
    { code: 'LOCK',      i18nKey: 'LOCK_WORKING' },
    { code: 'FLOOR',     i18nKey: 'FLOOR_OK' },
    { code: 'WALLS',     i18nKey: 'WALLS_OK' },
    { code: 'DAMP',      i18nKey: 'NO_DAMP' },
    { code: 'DAMAGE',    i18nKey: 'NO_DAMAGE' },
    { code: 'TENANT_OK', i18nKey: 'TENANT_CONFIRM' },
  ],
  move_out: [
    { code: 'PHOTOS',   i18nKey: 'PHOTOS_UPLOADED' },
    { code: 'EMPTY',    i18nKey: 'UNIT_EMPTY' },
    { code: 'CLEAN',    i18nKey: 'UNIT_CLEAN' },
    { code: 'DAMAGE',   i18nKey: 'NO_NEW_DAMAGE' },
    { code: 'CLEANING', i18nKey: 'CLEANING_REQUIRED' },
    { code: 'REPAIR',   i18nKey: 'REPAIR_REQUIRED' },
    { code: 'DEPOSIT',  i18nKey: 'DEPOSIT_ASSESSED' },
    { code: 'STATUS',   i18nKey: 'RETURN_STATUS' },
  ],
  routine: [
    { code: 'PHOTOS', i18nKey: 'PHOTOS_UPLOADED' },
    { code: 'DOOR',   i18nKey: 'DOOR_WORKING' },
    { code: 'LOCK',   i18nKey: 'LOCK_WORKING' },
    { code: 'FLOOR',  i18nKey: 'FLOOR_OK' },
    { code: 'WALLS',  i18nKey: 'WALLS_OK' },
    { code: 'DAMP',   i18nKey: 'NO_DAMP' },
    { code: 'CLEAN',  i18nKey: 'UNIT_CLEAN' },
    { code: 'DAMAGE', i18nKey: 'NO_DAMAGE_OBSERVED' },
  ],
};
